blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/didiladi/allergy-tracker/discussions
    about: Ask questions or discuss ideas in the Discussions tab
